kind: Route
apiVersion: v1
metadata:
  name: ${this@name}
  labels:
    application: ${this@name}
spec:
  host: ${this@name}.apps.${this@cluster.url.base}
  to:
    kind: Service
    name: ${this@name}
    weight: 100
{{#ssl.enable}}
  tls:
    termination: passthrough
{{/ssl.enable}}